const { Model, DataTypes } = require('sequelize');
const getConnexion = require('./getConnexion');

class Food extends Model {}

Food.init(
  {
    code: {
      type: DataTypes.INTEGER,
      unique: true,
      autoIncrement: true,
      primaryKey: true
    },
    name_fr: DataTypes.STRING,
    energy_kj_ue_1169_2011: DataTypes.STRING,
    energy_kcal_ue_1169_2011: DataTypes.STRING,
    energy_kj_jones_factor: DataTypes.STRING,
    energy_kcal_jones_factor: DataTypes.STRING,
    water: DataTypes.STRING,
    protein_jones_factor: DataTypes.STRING,
    protein_6_25: DataTypes.STRING,
    carbohydrate: DataTypes.STRING,
    lipid: DataTypes.STRING,
    sugar: DataTypes.STRING,
    fructose: DataTypes.STRING,
    galactose: DataTypes.STRING,
    glucose: DataTypes.STRING,
    lactose: DataTypes.STRING,
    maltose: DataTypes.STRING,
    sucrose: DataTypes.STRING,
    starch: DataTypes.STRING,
    fibre: DataTypes.STRING,
    polyol: DataTypes.STRING,
    ash: DataTypes.STRING,
    alcohol: DataTypes.STRING,
    organic_acid: DataTypes.STRING,
    fatty_acid_saturated: DataTypes.STRING,
    fatty_acid_monounsaturated: DataTypes.STRING,
    fatty_acid_polyunsaturated: DataTypes.STRING,
    fatty_acid_butyric: DataTypes.STRING,
    fatty_acid_caproic: DataTypes.STRING,
    fatty_acid_caprylic: DataTypes.STRING,
    fatty_acid_capric: DataTypes.STRING,
    fatty_acid_lauric: DataTypes.STRING,
    fatty_acid_myristic: DataTypes.STRING,
    fatty_acid_palmitic: DataTypes.STRING,
    fatty_acid_stearic: DataTypes.STRING,
    fatty_acid_oleic: DataTypes.STRING,
    fatty_acid_linoleic: DataTypes.STRING,
    fatty_acid_alpha_linoleic: DataTypes.STRING,
    fatty_acid_arachidonic: DataTypes.STRING,
    fatty_acid_epa: DataTypes.STRING,
    fatty_acid_dha: DataTypes.STRING,
    cholesterol: DataTypes.STRING,
    salt: DataTypes.STRING,
    calcium: DataTypes.STRING,
    chloride: DataTypes.STRING,
    copper: DataTypes.STRING,
    iron: DataTypes.STRING,
    iodine: DataTypes.STRING,
    magnesium: DataTypes.STRING,
    manganese: DataTypes.STRING,
    phosphorus: DataTypes.STRING,
    potassium: DataTypes.STRING,
    selenium: DataTypes.STRING,
    sodium: DataTypes.STRING,
    zinc: DataTypes.STRING,
    retinol: DataTypes.STRING,
    beta_carotene: DataTypes.STRING,
    vitamin_d: DataTypes.STRING,
    vitamin_e: DataTypes.STRING,
    vitamin_k1: DataTypes.STRING,
    vitamin_k2: DataTypes.STRING,
    vitamin_c: DataTypes.STRING,
    vitamin_b1: DataTypes.STRING,
    vitamin_b2: DataTypes.STRING,
    vitamin_b3: DataTypes.STRING,
    vitamin_b5: DataTypes.STRING,
    vitamin_b6: DataTypes.STRING,
    vitamin_b9: DataTypes.STRING,
    vitamin_b12: DataTypes.STRING,
  },
  {
    sequelize: getConnexion(),
    modelName: 'Food',
    tableName: 'food',
    timestamps: false
  }
)

module.exports = Food;
